### ISSUE TITLE
2D Array DDS With Mipmaps error on import

### ISSUE THREAD

**Issue by GameOverloads** [matyalatte/Blender-DDS-Addon#16]
Just a simple thing, DDS arrays with mipmaps do not import due to being 'unexpected'.

**Comment by matyalatte** [comment]
Can you share the DDS arrays with mipmaps? Or a tool can read and write them?
I think I can support them but I don't have any test cases.

**Comment by GameOverloads** [comment]
Do you have a Discord I can discuss and share files with you in to make this easier?

**Comment by matyalatte** [comment]
I'm in some modding servers like [Unreal Engine Modding](https://discord.com/invite/unreal-engine-modding-876613187204685934).
You can search matyamodding in the servers.

**Comment by matyalatte** [comment]
Fixed at b3f35ec573d677c7a56b761c9c15dd88e24fa86a.
The fixed version will be released as v0.3.5.
