### ISSUE TITLE
Certain DDS Files Not Including Alpha On Import

### ISSUE THREAD

**Issue by GameOverloads** [matyalatte/Blender-DDS-Addon#18]
Game: Helldivers 2
Texture Type: Material LUT
Imported Format: RGBA16 UNORM

*DM Sent As Well, So You Know

**Comment by matyalatte** [comment]
Thanks for the report.
Confirmed that my dds addon removed alpha from `R16G16B16A16_FLOAT` and `R32G32B32A32_FLOAT`.
The addon converts float formats to `.hdr` that doesn't support alpha.
So, I need to make a new function to read uncompressed data as it is.

**Comment by matyalatte** [comment]
Fixed at b06516379923241ca8fc1fedca3f2eb75b04d6b2 and 9c2e8d6d33453ed02aa8e23bd2a84772c8e71d10.
